# Generated by Django 2.0.2 on 2018-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banqueting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccaccount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ccanagrafica',
            options={'managed': True},
        ),
    ]
